// <auto-generated />
using System;
using ClassLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassLibrary.Migrations
{
    [DbContext(typeof(CegContext))]
    partial class CegContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ClassLibrary.Models.Alkalmazott", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Belepes")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Beosztas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Fizetes")
                        .HasColumnType("int");

                    b.Property<int>("FonokId")
                        .HasColumnType("int");

                    b.Property<int>("Jutalom")
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("OsztalyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Alkalmazott");
                });
#pragma warning restore 612, 618
        }
    }
}
